application: bionic-charge-93718
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /images
  static_dir: images

- url: /.*
  script: content.application


libraries:
- name: jinja2
  version: latest
